/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package optimaizer;

import com.sun.jna.platform.win32.Advapi32;
import com.sun.jna.platform.win32.WinNT;
import com.sun.jna.platform.win32.WinReg;
import com.sun.jna.ptr.IntByReference;
import java.io.IOException;
import utility.DeleteFiles;
import utility.DisableNotifications;
import utility.DisableApps;
import com.sun.jna.Native;
import com.sun.jna.platform.win32.Kernel32;
import com.sun.jna.platform.win32.WinNT.HANDLE;
import com.sun.jna.win32.StdCallLibrary;
import com.sun.jna.ptr.IntByReference;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author n3v3rm1nd
 */
public class Window extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
        showFilesSO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_desableApps = new javax.swing.JButton();
        btn_desableNoti = new javax.swing.JButton();
        btn_deleteFiles = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_desableApps.setText("Eliminar Apps en 2º plano");
        btn_desableApps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desableAppsActionPerformed(evt);
            }
        });

        btn_desableNoti.setText("Eliminar Notificaciones");
        btn_desableNoti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desableNotiActionPerformed(evt);
            }
        });

        btn_deleteFiles.setText("Eliminar archivos basura");
        btn_deleteFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteFilesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(342, 342, 342)
                .addComponent(btn_desableApps, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148)
                .addComponent(btn_deleteFiles, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(82, 82, 82)
                    .addComponent(btn_desableNoti, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(855, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_deleteFiles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_desableApps, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                .addContainerGap(394, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addComponent(btn_desableNoti, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(392, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_desableAppsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_desableAppsActionPerformed
        // TODO add your handling code here:
        DisableApps dn = new DisableApps();
        dn.disable();
    }//GEN-LAST:event_btn_desableAppsActionPerformed

    private void btn_desableNotiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_desableNotiActionPerformed
        // TODO add your handling code here:
        DisableNotifications dn = new DisableNotifications();
        dn.disable();
    }//GEN-LAST:event_btn_desableNotiActionPerformed

    private void btn_deleteFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteFilesActionPerformed
        try {
            // TODO add your handling code here:
            DeleteFiles df = new DeleteFiles();
            //df.deleteFile("C:\\Users\\n3v3rm1nd\\AppData\\Local\\Temp");
            String user = System.getProperty("user.name");
            df.deleteFile("C:\\Users\\" + user + "\\AppData\\Local\\Temp");
            df.deleteFile("C:\\Windows\\Temp");
            df.deleteFile("C:\\Windows\\Prefetch");
            df.deleteFile("C:\\Windows\\SoftwareDistribution\\Download");
            df.deleteFile("C:\\Windows\\Logs");
            Thread.sleep(2000);
            rebootService();
            Thread.sleep(2000);
            System.out.println(getCurrentUserSID());
            df.deleteFile("C:\\$Recycle.Bin\\" + getCurrentUserSID());
            Thread.sleep(2000);
            hideFilesSO();
            Thread.sleep(2000);
            rebootService();
        } catch (InterruptedException ex) {
            Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_deleteFilesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }
    
    public void showFilesSO(){
        WinReg.HKEYByReference hKey = new WinReg.HKEYByReference();
        int rc = Advapi32.INSTANCE.RegOpenKeyEx(WinReg.HKEY_CURRENT_USER, "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",0, WinNT.KEY_SET_VALUE, hKey);

        if (rc == 0) {  // ERROR_SUCCESS = 0
            // Escribir el valor ToastEnabled = 0 (desactivar notificaciones)
            int value = 1;
            IntByReference valueRef = new IntByReference(value);
            rc = Advapi32.INSTANCE.RegSetValueEx(hKey.getValue(), "ShowSuperHidden", 0, WinNT.REG_DWORD, valueRef.getPointer(), 4);

            if (rc == 0) {
                System.out.println("Archivos mostrados.");
            } else {
                System.out.println("Error al modificar el valor del registro.");
            }

            Advapi32.INSTANCE.RegCloseKey(hKey.getValue());
        } else {
            System.out.println("Error al abrir la clave del registro.");
        }
    }
    
    public void hideFilesSO(){
        WinReg.HKEYByReference hKey = new WinReg.HKEYByReference();
        int rc = Advapi32.INSTANCE.RegOpenKeyEx(WinReg.HKEY_CURRENT_USER, "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",0, WinNT.KEY_SET_VALUE, hKey);

        if (rc == 0) {  // ERROR_SUCCESS = 0
            // Escribir el valor ToastEnabled = 0 (desactivar notificaciones)
            int value = 0;
            IntByReference valueRef = new IntByReference(value);
            rc = Advapi32.INSTANCE.RegSetValueEx(hKey.getValue(), "ShowSuperHidden", 0, WinNT.REG_DWORD, valueRef.getPointer(), 4);

            if (rc == 0) {
                System.out.println("Archivos ocultos.");
            } else {
                System.out.println("Error al modificar el valor del registro.");
            }

            Advapi32.INSTANCE.RegCloseKey(hKey.getValue());
        } else {
            System.out.println("Error al abrir la clave del registro.");
        }
    }
    
    public static void rebootService() {
        try {
            // Ejecuta el comando de reinicio en Windows
            Process p  = Runtime.getRuntime().exec("taskkill /f /im explorer.exe");
            p.waitFor();
            Runtime.getRuntime().exec("cmd /c start explorer.exe");
        } catch (IOException e) {
            e.printStackTrace();
        } catch (InterruptedException ex) {
            Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public static String getCurrentUserSID() {
        String username = System.getProperty("user.name");  // Obtener el nombre de usuario actual
        String sid = null;

        try {
            // Ejecutar el comando wmic para obtener el SID del usuario actual
            Process process = new ProcessBuilder("wmic", "useraccount", "where", "name='" + username + "'", "get", "sid").start();
            BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));

            String line;
            while ((line = reader.readLine()) != null) {
                if (line.trim().startsWith("S-1-")) {  // El SID comienza con "S-1-"
                    sid = line.trim();  // Almacenar el SID
                    break;
                }
            }
            process.waitFor();  // Esperar a que el proceso termine
        } catch (Exception e) {
            e.printStackTrace();
        }

        return sid;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_deleteFiles;
    private javax.swing.JButton btn_desableApps;
    private javax.swing.JButton btn_desableNoti;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
